FROM maven:3.9.6-eclipse-temurin-21-jammy AS build
COPY hello-world /source
WORKDIR /source
RUN mvn clean package

#FROM eclipse-temurin:21-jre-jammy
#COPY --from=build /source/target/hello-world-0.0.1-SNAPSHOT.jar /app/hello-world.jar
EXPOSE 8080

CMD ["java","-jar","/source/target/hello-world-0.0.1-SNAPSHOT.jar"]
